#!/usr/bin/env node

var mazeFileName = process.argv[2];
var readline = require('readline');
var mazeLogic = require('./mazeLogic');
var chalk = require('chalk');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

mazeLogic.init(mazeFileName);
var next = {};

var startRoom = mazeLogic.start();

var gameLoop = function(currentRoom) {
  if(currentRoom.treasure) {
    console.log(chalk.red.bgGreen('You found the treasure!'));
    rl.close();
  } else {
    console.log('You are standing in a room. There are %d doors.', currentRoom.doorCount);
	
    var doorLocationString = '';
    var doorBoilerplate = 'One is to the ';
    if(currentRoom.north) {
      doorLocationString += doorBoilerplate + 'north. ';
    }
    if(currentRoom.west) {
      doorLocationString += doorBoilerplate + 'west. ';
    }
    if(currentRoom.east) {
      doorLocationString += doorBoilerplate + 'east. ';
    }
    if(currentRoom.south) {
      doorLocationString += doorBoilerplate + 'south. ';
    }
    console.log(doorLocationString);

  	rl.question('Which direction do you want to go? ', function(direction) {
      next = mazeLogic.nextRoom(currentRoom, direction);
      console.log('');
      if(next) {
        gameLoop(next);
      } else {
        console.log('You cannot go in that direction!');
        console.log('');
        gameLoop(currentRoom);
      }
    });
  }
};

gameLoop(startRoom);